name: todo_app_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

